main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nav.urls'), name='dyna'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nav/urls.py
from . import views
from django.urls import path


app_name = 'nav'

urlpatterns = [
    path('', views.dyna, name='dyna'),
    path('dyna', views.dyna, name='dyna'),
    path('acrylicpaintings/', views.acrylicpaintings, name='acrylicpaintings'),
    path('pastelpaintings/', views.pastelpaintings, name='pastelpaintings'),
    path('inkpaintings/', views.inkpaintings, name='inkpaintings'),


]

nav/models.py
from django.db import models


class AbstractPainting(models.Model):
    painting_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=2000)
    integer = models.IntegerField(blank=True, null=True)
    artist = models.CharField(max_length=100)
    image = models.ImageField()

    def __str__(self):
        return self.name


class AcrylicPainting(models.Model):
    name = models.CharField(max_length=2000)
    integer = models.IntegerField(blank=True, null=True)
    artist = models.CharField(max_length=100)
    image = models.ImageField()

    def __str__(self):
        return self.name


class PastelPainting(models.Model):
    name = models.CharField(max_length=2000)
    integer = models.IntegerField(blank=True, null=True)
    artist = models.CharField(max_length=100)
    image = models.ImageField()

    def __str__(self):
        return self.name


class InkPainting(models.Model):
    name = models.CharField(max_length=2000)
    integer = models.IntegerField(blank=True, null=True)
    artist = models.CharField(max_length=100)
    image = models.ImageField()

    def __str__(self):
        return self.name

nav/views.py
from django.shortcuts import render
from .models import AbstractPainting, AcrylicPainting, PastelPainting, InkPainting


# Create your views here.


def dyna(request):
    painting = AbstractPainting.objects.all()
    return render(request, "base.html", {"painting": painting})


def acrylicpaintings(request):
    acrylicpainting = AcrylicPainting.objects.all()
    return render(request, "acrylic.html", {"acrylicpainting": acrylicpainting})


def pastelpaintings(request):
    pastelpainting = PastelPainting.objects.all()
    return render(request, "pastel.html", {"pastelpainting": pastelpainting})

def inkpaintings(request):
    inkpainting = InkPainting.objects.all()
    return render(request, "ink.html", {"inkpainting": inkpainting})

nav/templates/acrylic.html
{% extends "base.html" %}


{% load static %}


{% block content %}

<div class="" style="padding-top:20px;  padding-left: 216px; ">
  <div class="row">
      {% for i in acrylicpainting %}
    <div class="col-sm">
<div class="mcard ">




            <div class="card" style=" background-color: #e3e3e3; width:316px; height:420px; padding-bottom: 20px; margin-bottom: 30px;">

                <img src="/media/{{i.image}}" width="316" height="316" alt="">
                <div class="container" >
                    <div ></div>
                    <h4><b>{{i.name}}</b></h4>
                    <p>{{i.artist}}  </p>


                          <a href="#"><button>Add to Cart</button></a>



                </div>



        </div>
    </div>
    </div>

      {% endfor %}
    </div>
    </div>



    {% endblock %}
<br>

nav/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
 <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"-->
<!--          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link href="{% static 'main/css/master.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Home</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <style>

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
    padding: 10px;
}


@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>

</head>
<body >


<div class="sidenav" >
  <a href="{% url 'nav:dyna' %}">Abstract</a>
  <a href="{% url 'nav:acrylicpaintings' %}">Acrylic</a>
  <a href="{% url 'nav:pastelpaintings' %}">Pastel</a>
  <a href="{% url 'nav:inkpaintings' %}">Ink</a>
</div>






<div class="" style="padding-top:20px;  padding-left: 216px; ">
  <div class="row">
      {% for i in painting %}
    <div class="col-sm">
<div class="mcard ">




            <div class="card" style=" background-color: #e3e3e3; width:316px; height:420px; padding-bottom: 20px; margin-bottom: 30px;">

                <img src="/media/{{i.image}}" width="316" height="316" alt="">
                <div class="container" >
                    <div ></div>
                    <h4><b>{{i.name}}</b></h4>
                    <p>{{i.artist}}  </p>


                          <a href="#"><button>Add to Cart</button></a>



                </div>



        </div>
    </div>
    </div>

      {% endfor %}
    </div>
    </div>


































<!--<div class="row">-->
<!--  <div class="column" >-->
<!--    <img src="{% static 'images/Drake_-_Signs_cover_nezbeu7.jpg' %}" alt="Snow" >-->
<!--    <div class="container" style="color: white; text-align: center;">-->
<!--        <h4><b>John Doe</b></h4>-->
<!--        <p>Architect & Engineer</p>-->
<!--      </div>-->
<!--  </div>-->
<!--  <div class="column" >-->
<!--    <img src="{% static 'images/Drake_-_Signs_cover_nezbeu7.jpg' %}" alt="Snow" >-->
<!--    <div class="container" style="color: white; text-align: center;">-->
<!--        <h4><b>John Doe</b></h4>-->
<!--        <p>Architect & Engineer</p>-->
<!--      </div>-->
<!--  </div>-->
<!--  <div class="column" >-->
<!--    <img src="{% static 'images/Drake_-_Signs_cover_nezbeu7.jpg' %}" alt="Snow" >-->
<!--    <div class="container" style="color: white; text-align: center;">-->
<!--        <h4><b>John Doe</b></h4>-->
<!--        <p>Architect & Engineer</p>-->
<!--      </div>-->
<!--  </div>-->

<!--</div>-->



{% block content %}

    {% endblock %}




</body>
</html>

nav/templates/ink.html
{% extends "base.html" %}


{% load static %}


{% block content %}

<div class="" style="padding-top:20px;  padding-left: 216px; ">
  <div class="row">
      {% for i in inkpainting %}
    <div class="col-sm">
<div class="mcard ">




            <div class="card" style=" background-color: #e3e3e3; width:316px; height:420px; padding-bottom: 20px; margin-bottom: 30px;">

                <img src="/media/{{i.image}}" width="316" height="316" alt="">
                <div class="container" >
                    <div ></div>
                    <h4><b>{{i.name}}</b></h4>
                    <p>{{i.artist}}</p>


                          <a href="#"><button>Add to Cart</button></a>



                </div>



        </div>
    </div>
    </div>

      {% endfor %}
    </div>
    </div>



    {% endblock %}
<br>

nav/templates/pastel.html
{% extends "base.html" %}


{% load static %}


{% block content %}

<div class="" style="padding-top:20px;  padding-left: 216px; ">
  <div class="row">
      {% for i in pastelpainting %}
    <div class="col-sm">
<div class="mcard ">




            <div class="card" style=" background-color: #e3e3e3; width:316px; height:420px; padding-bottom: 20px; margin-bottom: 30px;">

                <img src="/media/{{i.image}}" width="316" height="316" alt="">
                <div class="container" >
                    <div ></div>
                    <h4><b>{{i.name}}</b></h4>
                    <p>{{i.artist}}</p>


                          <a href="#"><button>Add to Cart</button></a>



                </div>



        </div>
    </div>
    </div>

      {% endfor %}
    </div>
    </div>



    {% endblock %}
<br>